version: '3.8'

services:
  # Сервис с базой данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: words_game
      POSTGRES_PASSWORD: yQMeKidypmQg4YWP902PotNKC5jrQo
      POSTGRES_DB: wordgamedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  # Сервис с вашим Next.js приложением
  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - internal_net

  # Сервис с веб-сервером Nginx
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Общие папки с Certbot
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - internal_net
    depends_on:
      - app

  # <<< НОВЫЙ СЕРВИС ДЛЯ CERTBOT >>>
  certbot:
    image: certbot/certbot
    # volumes используются для того, чтобы Certbot мог создавать файлы сертификатов,
    # которые Nginx потом сможет прочитать.
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # Сервису Certbot не нужно открывать порты наружу

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data: