services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: words_game
      POSTGRES_PASSWORD: yQMeKidypmQg4YWP902PotNKC5jrQo
      POSTGRES_DB: wordgamedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://words_game:yQMeKidypmQg4YWP902PotNKC5jrQo@db:5432/wordgamedb"
    networks:
      - internal_net

  # NGINX
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Убедитесь, что у вас есть папка nginx с этим файлом конфигурации
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Папки для работы Certbot и хранения сертификатов
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - internal_net
    depends_on:
      - app

  # CERTBOT
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data:
