version: '3.8'

services:
  # Сервис с базой данных PostgreSQL
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      # ВАЖНО: Эти значения должны совпадать с теми, что вы указали в DATABASE_URL в файле .env.local
      POSTGRES_USER: words_game
      POSTGRES_PASSWORD: yQMeKidypmQg4YWP902PotNKC5jrQo
      POSTGRES_DB: wordgamedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  # Сервис с вашим Next.js приложением
  app:
    build: . # Собираем образ из Dockerfile в текущей папке
    restart: always
    depends_on:
      - db
    environment:
      # Пробрасываем переменную из .env.local внутрь контейнера
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - internal_net

  # Сервис с веб-сервером Nginx
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"   # Для HTTP и первого получения сертификата
      - "443:443" # Для HTTPS
    volumes:
      # Подключаем нашу конфигурацию Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # Подключаем папки для сертификатов Let's Encrypt
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - internal_net
    depends_on:
      - app

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data: