services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: words_game
      POSTGRES_PASSWORD: yQMeKidypmQg4YWP902PotNKC5jrQo
      POSTGRES_DB: wordgamedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  app:
    build: . # Сборка из корневого Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data: