// frontend/src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProgressProvider } from "@/context/ProgressContext"; // <-- ИМПОРТ

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <<< ОБЕРТКА ЗДЕСЬ >>> */}
        <ProgressProvider>
          {children}
        </ProgressProvider>
      </body>
    </html>
  );
}